[package]
name = "nativefier_tauri"
description = "Create lightweight desktop applications of any website; but with Rust and Tauri."
version = "0.1.3"
edition = "2021"
license = "MIT"

[dependencies]
home = "0.5.4"
